POC pre-checkout plugin

diff --git a/hooks/pre-checkout b/hooks/pre-checkout
--- a/hooks/pre-checkout
+++ b/hooks/pre-checkout
@@ -4,17 +4,35 @@ set -euo pipefail
 
 set -x
 
-echo "Checking integration permissions..."
-aws sts get-caller-identity
-aws s3 ls s3://com.rippling.cde-backup/boggsboggs/
+# Example BUILDKITE_REPO="git@github.com:Rippling/rippling-main.git"
+REPO_NAME=${BUILDKITE_REPO##*/} #Strip up to the last '/'
 
-git clone git@github.com:Rippling/rippling-main.git
+S3_CACHE_ROOT="s3://com.rippling.cde-backup/boggsboggs/git-cache"
+S3_REPO_PATH="${S3_CACHE_ROOT}/${REPO_NAME}"
 
-ls $BUILDKITE_GIT_MIRRORS_PATH
+TMP_STORAGE_DIR="/tmp/git-cache-tmp-repo-storage"
+TMP_STORAGE_PATH="${TMP_STORAGE_DIR}/${REPO_NAME}.tar"
 
-echo $BUILDKITE_COMMIT
-echo $BUILDKITE_BUILD_CHECKOUT_PATH
 
-ls $BUILDKITE_BUILD_CHECKOUT_PATH
+if ! [ -f "$BUILDKITE_BUILD_CHECKOUT_PATH/.git" ]; then
+  echo "Need to download or clone ${REPO_NAME}"
 
-ls $BUILDKITE_BUILD_CHECKOUT_PATH/.git
+  # Try to download it from S3
+  echo "Attempting S3 download..."
+  if ! aws s3 cp "$S3_REPO_PATH" "$TMP_STORAGE_PATH"
+    echo "Failed to download from S3."
+    echo "Running git clone..."
+    git clone $BUILDKITE_GIT_CLONE_FLAGS "$BUILDKITE_REPO" "$BUILDKITE_BUILD_CHECKOUT_PATH"
+
+    echo "Updating S3 Cache..."
+    tar -cxf "$TMP_STORAGE_PATH" "$BUILDKITE_BUILD_CHECKOUT_PATH"
+    s3 cp "$TMP_STORAGE_PATH" "$S3_REPO_PATH"
+    exit 0
+  fi
+
+  echo "Unarchiving..."
+  tar -xvf "$TMP_STORAGE_PATH" "$BUILDKITE_BUILD_CHECKOUT_PATH"
+  echo "Done."
+else
+  echo "Git repo already exists at $BUILDKITE_BUILD_CHECKOUT_PATH/.git, nothing to do."
+fi
